version: '3.8'

services:

  db:
    container_name: postgres_db
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: nEvt1kJu4ra_y8$2QLzt
      POSTGRES_DB: absen_db
      TZ: Asia/Jakarta
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      vpcbr:
        ipv4_address: 10.10.1.2
        
volumes:
  postgres_data:

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1
