version: '3.8'

services:
  django_app:
    container_name: app
    build:
      context: ./
    volumes:
      - static_file:/code/staticfiles
      - media_file:/code/media
        #ports:
        #- 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - pgadmin
    networks:
      - vpcbr

  nginx:
    container_name: reverse_proxy
    build:
      context: ./nginx/
    volumes:
      - static_file:/static
      - media_file:/media
    ports:
      - "1415:80"
    depends_on:
      - django_app
    networks:
      - vpcbr

  db:
    container_name: postgres_db
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: absen
      POSTGRES_PASSWORD: root
      POSTGRES_DB: absen_db
      TZ: Asia/Jakarta
    ports:
      - "5432:5432"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admindb@example.com
      PGADMIN_DEFAULT_PASSWORD: smkn1cbn_0541
      TZ: Asia/Jakarta
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3


volumes:
  postgres_data:
  static_file:
  media_file:

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1
