# Generated by Django 3.2.8 on 2021-10-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('absen', '0003_auto_20211025_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinrecord',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee'),
        ),
        migrations.AlterField(
            model_name='checkoutrecord',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee'),
        ),
        migrations.AlterField(
            model_name='days',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee'),
        ),
        migrations.AlterField(
            model_name='role',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee'),
        ),
        migrations.AlterField(
            model_name='tempimage',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
