# Generated by Django 3.2.8 on 2021-10-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0004_auto_20211025_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
