# Generated by Django 3.2.8 on 2021-10-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0005_delete_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Days',
        ),
    ]
