# Generated by Django 3.2.8 on 2021-10-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_remove_employee_photo'),
        ('absen', '0006_delete_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimage',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.employee'),
        ),
    ]
