# Generated by Django 3.2.8 on 2021-10-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0007_alter_tempimage_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='checkin_desc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='presence',
            name='checkin_img',
            field=models.ImageField(blank=True, upload_to='checkin/'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='checkout_desc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='presence',
            name='checkout_img',
            field=models.ImageField(blank=True, upload_to='checkout/'),
        ),
    ]
