# Generated by Django 3.2.8 on 2021-10-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0008_auto_20211029_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempImage',
        ),
    ]
