# Generated by Django 3.2.8 on 2021-11-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0010_auto_20211031_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinrecord',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutrecord',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
