# Generated by Django 3.2.8 on 2021-11-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0012_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
