# Generated by Django 3.2.8 on 2022-01-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0014_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
