# Generated by Django 3.2.8 on 2022-03-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0015_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='checkin_desc',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='checkout_desc',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
