# Generated by Django 3.2.8 on 2022-03-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0015_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
