# Generated by Django 3.2.8 on 2021-11-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0008_remove_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HumanDevelopmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HumanDevelopmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InnovativeWorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MajorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScientificWorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.classname')),
            ],
        ),
        migrations.CreateModel(
            name='StudyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_student', models.IntegerField()),
                ('presence_student', models.IntegerField()),
                ('absent_student', models.IntegerField()),
                ('documentation', models.FileField(upload_to='study_report/')),
                ('desc', models.CharField(blank=True, max_length=512, null=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.classname')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.method')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.subjectname')),
            ],
        ),
        migrations.CreateModel(
            name='ScientificWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documentation', models.FileField(upload_to='scientific_work_report/')),
                ('desc', models.TextField(blank=True, max_length=512, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.scientificworkcategory')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee')),
            ],
        ),
        migrations.CreateModel(
            name='InnovativeWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documentation', models.FileField(upload_to='innovative_work_report/')),
                ('desc', models.TextField(blank=True, max_length=512, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.innovativeworkcategory')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HumanDevelopmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=2)),
                ('documentation', models.FileField(upload_to='human_development_report/')),
                ('desc', models.TextField(blank=True, max_length=512, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.humandevelopmentcategory')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.humandevelopmentrole')),
            ],
        ),
        migrations.CreateModel(
            name='GuidanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documentation', models.FileField(upload_to='guidance_report/')),
                ('desc', models.TextField(blank=True, max_length=512, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DutyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documentation', models.FileField(upload_to='duty_report/')),
                ('desc', models.TextField(blank=True, max_length=512, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.majorrole')),
            ],
        ),
    ]
