# Generated by Django 3.2.8 on 2021-11-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0005_studyreport_subjectname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyreport',
            old_name='subject',
            new_name='subject_name',
        ),
        migrations.AddField(
            model_name='studyreport',
            name='subject_category',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
