# Generated by Django 3.2.8 on 2021-11-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0006_auto_20211114_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyreport',
            old_name='absent_student',
            new_name='absence_student',
        ),
    ]
