# Generated by Django 3.2.8 on 2021-11-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0007_rename_absent_student_studyreport_absence_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidancereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
