# Generated by Django 3.2.8 on 2021-11-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0009_alter_guidancereport_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovativeworkreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
