# Generated by Django 3.2.8 on 2021-11-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0011_alter_scientificworkreport_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificworkreport',
            name='documentation',
            field=models.FileField(null=True, upload_to='scientific_work_report/'),
        ),
    ]
