# Generated by Django 3.2.8 on 2021-11-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0013_alter_scientificworkreport_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humandevelopmentreport',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='humandevelopmentreport',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='HumanDevelopmentCategory',
        ),
        migrations.DeleteModel(
            name='HumanDevelopmentRole',
        ),
    ]
