# Generated by Django 3.2.8 on 2021-11-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0014_auto_20211116_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='humandevelopmentreport',
            name='held_on',
            field=models.DateField(null=True),
        ),
    ]
