# Generated by Django 3.2.8 on 2021-11-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0016_alter_humandevelopmentreport_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyreport',
            name='method',
            field=models.CharField(max_length=255),
        ),
    ]
