# Generated by Django 3.2.8 on 2022-03-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0017_alter_studyreport_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='innovativeworkcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='majorrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='scientificworkcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
