name: Deployment

on:
  workflow_run:
    workflows:
      - "Django CI"
    types:
      - completed

jobs:
  build:
    name: deploy to server over ssh command
    runs-on: ubuntu-20.04

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_PROD_USER }}
          port: ${{ secrets.SSH_PROD_PORT }}
          key: ${{ secrets.SSH_PROD_KEY }}
          passphrase: ${{ secrets.SSH_PROD_PASSPHRASE }}
          script: |
            cd absensi-guru-django/
            bash deploy.sh
