# Generated by Django 3.2.8 on 2021-10-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
