# Generated by Django 3.2.8 on 2021-10-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_employee_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
