# Generated by Django 3.2.8 on 2022-02-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_remove_employee_photo'),
    ]

    operations = [
    ]
