# Generated by Django 3.2.8 on 2022-03-06 13:43
# Generated by Django 3.2.8 on 2022-03-06 13:14

from django.db import migrations

# Generated by Django 3.2.8 on 2022-02-09 03:19

from django.db import migrations, models
from django.conf import settings
import csv

def classes_migration(apps, schema_editor):
    class_name = apps.get_model('laporan', 'ClassName')
    with open(settings.MEDIA_ABS_PATH + '/foreign/classname.csv', 'r') as class_file:
        class_read = csv.reader(class_file, delimiter=',')
        for row in class_read:
            class_name.objects.create(id=row[0],
                                        class_name=row[1])
            
def major_role_migration(apps, schema_editor):
    major_role = apps.get_model('laporan', 'MajorRole')
    with open(settings.MEDIA_ABS_PATH, '/foreign/majorrole.csv', 'r') as mrole_file:
        mrole_read = csv.reader(mrole_file, delimiter=',')
        for row in mrole_read:
            major_role.objects.create(id=row[0],
                                    role_name=row[1])
            
def subject_category_migration(apps, schema_editor):
    subject_category = apps.get_model('laporan', 'SubjectCategory')
    with open(settings.MEDIA_ABS_PATH + '/foreign/subjectcat.csv', 'r') as subcat_file:
        subcat_read = csv.reader(subcat_file, delimiter=',')
        for row in subcat_read:
            subject_category.objects.create(id=row[0],
                                            category=row[1])
            
def study_method_migration(apps, schema_editor):
    method = apps.get_model('laporan', 'Method')
    with open(settings.MEDIA_ABS_PATH + '/foreign/method.csv', 'r') as method_file:
        method_read = csv.reader(method_file, delimiter=',')
        for row in method_read:
            method.objects.create(id=row[0],
                                    method_name=row[1])
            
def scientific_category_migration(apps, schema_editor):
    category = apps.get_model('laporan', 'ScientificWorkCategory')
    with open(settings.MEDIA_ABS_PATH + '/foreign/scientificworkcat.csv', 'r') as scat_file:
        scat_read = csv.reader(scat_file, delimiter=',')
        for row in scat_read:
            category.objects.create(id=row[0],
                                    category_name=row[1])
            
def innovative_category_migration(apps, schema_editor):
    category = apps.get_model('laporan', 'InnovativeWorkCategory')
    with open(settings.MEDIA_ABS_PATH + '/foreign/innovativeworkcat.csv', 'r') as icat_file:
        icat_read = csv.reader(icat_file, delimiter=',')
        for row in icat_read:
            category.objects.create(id=row[0],
                                    category_name=row[1])
    

class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_auto_20220209_0807'),
    ]

    operations = [
        migrations.RunPython(classes_migration),
        migrations.RunPython(subject_category_migration),
        migrations.RunPython(study_method_migration),
        migrations.RunPython(scientific_category_migration),
        migrations.RunPython(innovative_category_migration),
    ]
