# Generated by Django 3.2.8 on 2022-03-06 13:43

# Generated by Django 3.2.8 on 2022-03-06 13:18

# Generated by Django 3.2.8 on 2022-02-09 04:18

from django.db import migrations, models
import csv
from django.conf import settings
from laporan.models import *

def subject_name_migration(apps, schema_editor):
    subject_name = apps.get_model('laporan', 'SubjectName')
    subject_category = apps.get_model('laporan', 'SubjectCategory')
    class_name = apps.get_model('laporan', 'ClassName')
    with open(settings.MEDIA_ABS_PATH + '/foreign/subjectname.csv', 'r') as subname_file:
        subname_read = csv.reader(subname_file, delimiter=',')
        for row in subname_read:
            category = SubjectCategory.objects.get(id=row[2]).id
            class_id = class_name.objects.get(id=row[3]).id
            subject_name.objects.create(id=row[0],
                                        subject_name=row[1],
                                        category_id=category,
                                        class_name_id=class_id)


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_auto_20220306_2043'),
    ]

    operations = [
        migrations.RunPython(subject_name_migration)
    ]
