# Generated by Django 3.2.8 on 2022-03-11 12:38

from django.db import migrations, models
import csv
from django.conf import settings
from laporan.models import *

def major_role_migration(apps, schema_editor):
    major_role = apps.get_model('laporan', 'MajorRole')
    with open(settings.MEDIA_ABS_PATH + '/foreign/majorrole.csv', 'r') as mrole_file:
        mrole_read = csv.reader(mrole_file, delimiter=',')
        for row in mrole_read:
            major_role.objects.create(id=row[0],
                                    role_name=row[1])

class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_auto_20220306_2043'),
    ]

    operations = [
        migrations.RunPython(major_role_migration)
    ]
