# Generated by Django 3.2.8 on 2022-03-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_auto_20220306_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
